version: 2

unit_tests: &unit_tests
  steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
    - run:
        name: Install pnpm
        command: npm install pnpm@^4.0.0 -g
    - run:
        name: Run unit tests.
        command: pnpm run ci:test

jobs:
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install pnpm@^4.0.0 -g
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm install --ignore-scripts
      - run:
          name: Run linting.
          command: pnpm run ci:lint
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
  node-v8-latest:
    docker:
      - image: rollupcabal/circleci-node-v8:latest
    <<: *unit_tests
  node-v10-latest:
    docker:
      - image: rollupcabal/circleci-node-v10:latest
    <<: *unit_tests
  node-v12-latest:
    docker:
      - image: rollupcabal/circleci-node-v12:latest
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
    - run:
        name: Install pnpm
        command: npm install pnpm@^4.0.0 -g
    - run:
        name: Run unit tests.
        command: pnpm run ci:coverage
    - run:
        name: Submit coverage data to codecov.
        command: pnpm run ci:coverage:submit
        when: on_success

workflows:
  version: 2
  validate-test:
    jobs:
      - analysis:
          filters:
            tags:
              only: /.*/
      # - node-v8-latest:
      #     requires:
      #       - analysis
      #     filters:
      #       tags:
      #         only: /.*/
      # - node-v10-latest:
      #     requires:
      #       - analysis
      #     filters:
      #       tags:
      #         only: /.*/
      - node-v12-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
