name: Node

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '10', '6' ]

    name: ${{ matrix.node }} (Windows)
    steps:
    - name: Configure git line-breaks
      run: git config --global core.autocrlf false
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install PNPM
      run: npm install pnpm -g
    - name: Install dependencies
      run: pnpm install --frozen-shrinkwrap
    - name: Run tests
      run: pnpm run test
      env:
        CI: true
